# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b68979ef098ab7b0371ad04575a7a5a570d58f2c2713273efcfcc6b8fa504ba39c1c39da86a49dd3531112d4d2d00ea3d631cbac986cf83dfc8bdfd787fef61d

test:
  secret_key_base: e3e8f5715fd6de5eb69b1638a82f628f346c47d9fcbaeff1c39817da7c77872c6d938f0bd6293cea8c63d4d849065bb630a2b5b48744b8b63d039511e545979e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
